#!/bin/bash 

quarantinePath="$HOME/toxic"
if [ ! -d "$quarantinePath" ]; then
  mkdir "$quarantinePath"
fi

filePath="$1"
if [ "${filePath##*.}" = "part" ]; then
  echo "$filePath: File is a partial download, ignoring"
  exit 0
fi

if [ -d "$filePath" ]; then
  echo "$filePath is a directory, ignoring"
  exit 0
fi

DISPLAY=:0.0 notify-send --expire-time 5000 -- "Scan Started" "$filePath"
clamscan -r --move "$quarantinePath" -- "$filePath"
case $? in
  0)
    DISPLAY=:0.0 notify-send --expire-time 5000 -- "Scan Completed" "$filePath is clean"
    ;;
  1)
    DISPLAY=:0.0 notify-send -u CRITICAL --expire-time 5000 -- "Virus Detected!" "$filePath is quarantined!"
    ;;
  2)
    DISPLAY=:0.0 notify-send -u CRITICAL --expire-time 5000 -- "Scan Errors" "$filePath scan completed with errors, see logfile"
    ;;
  default)
    DISPLAY=:0.0 notify-send -u CRITICAL --expire-time 5000 -- "Scan Errors" "$filePath scan completed with weird exit code"
    ;;
esac
